let suggestions = [
    "java Introduction",
    "Control Statements",
    "Object Class",
    "Inheritance ",
    "Polymorphism ",
    "Abstraction ",
    "Encapsulation ",
    "java Examples",
    "Introduction",
    "Flow control" ,        
    "Functions"     ,      
    " File Handling" ,        
    "class&objects",
    "Python Examples",
    "Introduction",
    "SQL SELECT(I)",          
    " SQL SELECT(II)" ,
    "SQL JOIN",
    "SQL Database",
    "SQL Insert and Delete" ,
    "SQL Constarints"
];